import { BriefcaseBusiness, GitBranch, ShieldCheck, Truck } from 'lucide-react';
import type {
  Hint,
  HealthyCheckpoint,
  HealthyChecklistItem,
  IncidentMissionDefinition,
  KnowledgeCheckQuestion,
  MissionCommunication,
  MissionPhase,
  TeachingStep,
  TrainingEntity,
  TrainingMission,
  TrainingRole,
} from './types';

export const TRAINING_ROLE: TrainingRole = 'Integration Support Analyst';
export const LEARN_THE_FLOW_MISSION_ID = 'LEARN_THE_FLOW';
export const APEX_BAD_AUTH_MISSION_ID = 'APEX_BAD_AUTH';
export const APEX_INVALID_JSON_MISSION_ID = 'APEX_INVALID_JSON';
export const APEX_INVALID_CONTRACT_MISSION_ID = 'APEX_INVALID_CONTRACT';
export const DUPLICATE_SHIPMENT_MISSION_ID = 'DUPLICATE_SHIPMENT';
export const X12_ENVELOPE_MISMATCH_MISSION_ID = 'X12_ENVELOPE_MISMATCH';
export const STATUS_CALLBACK_MISSING_MISSION_ID = 'STATUS_CALLBACK_MISSING';
export const WRONG_X12_VERSION_MISSION_ID = 'WRONG_X12_VERSION';
export const PLANNED_MISSION_COUNT = 10;

export const trainingMissions: TrainingMission[] = [
  {
    id: LEARN_THE_FLOW_MISSION_ID,
    slug: 'learn-the-flow',
    title: 'Mission 1 - Your First Shift',
    subtitle: 'Watch a Healthy Integration',
    difficulty: 'ORIENTATION',
    summary: 'Start inside FreightBridge and watch one clean shipment from the evidence your team can actually observe.',
    implemented: true,
  },
  {
    id: APEX_BAD_AUTH_MISSION_ID,
    slug: 'apex-bad-auth',
    title: "Mission 2 - Apex Can't Get a Load Through",
    difficulty: 'BEGINNER',
    summary: 'Investigate why an Apex load tender stops before downstream processing, then verify a safe recovery.',
    implemented: true,
    unlocksAfter: LEARN_THE_FLOW_MISSION_ID,
  },
  {
    id: APEX_INVALID_JSON_MISSION_ID,
    slug: 'apex-invalid-json',
    title: "Mission 3 - The Request Arrived, But FreightBridge Can't Read It",
    difficulty: 'BEGINNER',
    summary: 'Separate successful request arrival and authentication from a payload that FreightBridge cannot parse.',
    implemented: true,
    unlocksAfter: APEX_BAD_AUTH_MISSION_ID,
  },
  {
    id: APEX_INVALID_CONTRACT_MISSION_ID,
    slug: 'apex-invalid-contract',
    title: 'Mission 4 - The JSON Looks Fine - Why Was It Rejected?',
    difficulty: 'BEGINNER',
    summary: 'Distinguish valid JSON from a load tender that fails FreightBridge contract validation.',
    implemented: true,
    unlocksAfter: APEX_INVALID_JSON_MISSION_ID,
  },
  {
    id: DUPLICATE_SHIPMENT_MISSION_ID,
    slug: 'duplicate-shipment',
    title: 'Mission 5 - Why Is This Shipment Showing Up Twice?',
    difficulty: 'INTERMEDIATE',
    summary: 'Correlate repeated Apex requests and distinguish duplicate business transactions from safe replay.',
    implemented: true,
    unlocksAfter: APEX_INVALID_CONTRACT_MISSION_ID,
  },
  {
    id: X12_ENVELOPE_MISMATCH_MISSION_ID,
    slug: 'x12-envelope-mismatch',
    title: 'Mission 6 - Midwest Sent the Status, But FreightBridge Rejected It',
    difficulty: 'INTERMEDIATE',
    summary: 'Inspect raw 214 control numbers and prove why file arrival did not mean parse success.',
    implemented: true,
    unlocksAfter: DUPLICATE_SHIPMENT_MISSION_ID,
  },
  {
    id: STATUS_CALLBACK_MISSING_MISSION_ID,
    slug: 'status-callback-missing',
    title: "Mission 7 - Midwest Sent the Status. Why Didn't Apex Get It?",
    difficulty: 'INTERMEDIATE',
    summary: 'Separate valid X12 parsing from unsupported Midwest 214 status mapping.',
    implemented: true,
    unlocksAfter: X12_ENVELOPE_MISMATCH_MISSION_ID,
  },
  {
    id: WRONG_X12_VERSION_MISSION_ID,
    slug: 'wrong-x12-version',
    title: 'Mission 8 - This Partner Is Sending the Wrong X12 Version',
    difficulty: 'ADVANCED',
    summary: 'Distinguish valid X12 structure from a 214 that conflicts with Midwest\'s active X12 version/profile.',
    implemented: true,
    unlocksAfter: STATUS_CALLBACK_MISSING_MISSION_ID,
  },
  {
    id: 'SFTP_STOPS_WORKING',
    slug: 'sftp-stops-working',
    title: 'Mission 9 - Midwest SFTP Suddenly Stops Working',
    difficulty: 'ADVANCED',
    summary: 'Locked roadmap placeholder for SFTP readiness and delivery failures.',
    implemented: false,
    unlocksAfter: 'WRONG_X12_VERSION',
  },
  {
    id: 'PRODUCTION_INCIDENT',
    slug: 'production-incident',
    title: 'Mission 10 - Production Incident',
    difficulty: 'FINAL SHIFT',
    summary: 'Locked final-shift scenario placeholder. No incident is implemented yet.',
    implemented: false,
    unlocksAfter: 'SFTP_STOPS_WORKING',
  },
];

export const trainingEntities: TrainingEntity[] = [
  {
    name: 'Apex Logistics',
    role: 'External Trading Partner - Broker / 3PL',
    perspective: 'external-partner',
    explanation: 'Apex has freight that needs to be moved and sends FreightBridge load requests.',
    communication: 'REST API + JSON. You can see the request FreightBridge received, not Apex internal logs.',
    icon: BriefcaseBusiness,
    testId: 'external-partner-apex',
  },
  {
    name: 'FreightBridge',
    role: 'Your Workplace - Integration Platform',
    perspective: 'learner-organization',
    explanation: 'FreightBridge connects trading partners that use different technologies and message formats.',
    communication: 'Receives, authenticates, validates, maps, translates, sends, tracks, and logs integration messages.',
    icon: ShieldCheck,
    testId: 'training-workplace-freightbridge',
  },
  {
    name: 'Midwest Carrier',
    role: 'External Trading Partner - Motor Carrier',
    perspective: 'external-partner',
    explanation: 'Midwest is the carrier that can accept the tender and physically move the freight.',
    communication: 'X12 004010 + SFTP. You can see files and responses FreightBridge exchanged, not Midwest private systems.',
    icon: Truck,
    testId: 'external-partner-midwest',
  },
];

export const firstShiftIntro: MissionCommunication = {
  kind: 'manager',
  from: 'Mike',
  role: 'Integration Manager',
  body:
    'Welcome aboard. Customers do not care that an API call failed or an EDI segment was wrong; they care that freight stopped moving. Your job is to prove what FreightBridge observed, explain where the flow stopped, and verify recovery. Before I give you incidents, I want you to see what normal looks like.',
};

export const missionOneBriefing: MissionCommunication = {
  kind: 'manager',
  from: 'Mike',
  role: 'Integration Manager',
  body:
    'Before I put you on an incident, I want you to know what a clean integration looks like. Follow one Apex load through FreightBridge and into Midwest. At every step, watch what we received, what FreightBridge did with it, and what evidence proves the next system received it. Later, when something breaks, you will compare the failed flow against this baseline.',
};

export const samplePartnerMessages: MissionCommunication[] = [
  {
    kind: 'partner',
    from: 'Apex Integration Support',
    role: 'External Partner Message',
    body: 'For production incidents, Apex would tell us what they sent and what response they received. FreightBridge still verifies that claim against our gateway and transaction evidence.',
  },
  {
    kind: 'partner',
    from: 'Midwest EDI Support',
    role: 'External Partner Message',
    body: 'For carrier-side questions, Midwest may report what their EDI team sees. FreightBridge treats that as partner communication, not direct access to Midwest internal systems.',
  },
];

export const missionOnePhases: MissionPhase[] = ['BRIEFING', 'INVESTIGATE', 'DEBRIEF'];

export const missionOneTimeline = [
  'Inbound request received from Apex',
  'Authentication passed',
  'JSON parsed',
  'Business validation passed',
  'Canonical shipment created',
  'Mapping selected',
  'X12 204 generated',
  'SFTP delivery attempted',
  'Midwest 997 received',
  'Midwest 990 received',
  'Midwest 214 received',
  'Apex callback sent',
];

export const missionOneHints: Hint[] = [
  {
    id: 'inbound',
    label: 'Hint 1 - Start with what FreightBridge received',
    body: 'For any partner complaint, first confirm whether FreightBridge received a request or file and which partner identity it used.',
  },
  {
    id: 'evidence',
    label: 'Hint 2 - Separate transport from business outcome',
    body: 'A 997 is transport/EDI structure evidence. The 990 is the carrier business decision.',
  },
  {
    id: 'status',
    label: 'Hint 3 - Check event time before received time',
    body: 'For shipment status, FreightBridge preserves event history and uses business event time to protect current status.',
  },
];

export const healthyCheckpoints: HealthyCheckpoint[] = [
  {
    id: 'inbound-apex',
    sequence: 1,
    title: 'Apex Reaches FreightBridge',
    shortLabel: 'Inbound',
    source: 'FreightBridge API Gateway',
    observed: 'Inbound REST/JSON request evidence from Apex Logistics.',
    whyItMatters: 'This proves the shipment reached the FreightBridge integration boundary. It does not prove Midwest has seen the load.',
    analystChecks: ['Partner identity is Apex Logistics', 'Transport is REST API', 'Format is JSON', 'A load/business identifier is present', 'No secrets or authorization values are exposed'],
    healthySignal: 'FreightBridge accepts the request into processing and creates correlated transaction evidence.',
    correlationFields: ['Load ID', 'Business Identifier', 'Lab Run ID'],
    questionId: 'inbound-does-not-prove-midwest',
  },
  {
    id: 'validation',
    sequence: 2,
    title: 'FreightBridge Accepts the Message',
    shortLabel: 'Validation',
    source: 'FreightBridge Inbound Processor',
    observed: 'Authentication, JSON parsing, partner identification, and business validation succeeded.',
    whyItMatters: 'Transport success only means a request arrived. Application validation proves FreightBridge can safely understand and process it.',
    analystChecks: ['Authentication passed', 'JSON was parseable', 'Required shipment fields are present', 'Business rules passed'],
    healthySignal: 'The inbound tender can move from raw partner request to canonical shipment processing.',
    correlationFields: ['Load ID', 'BOL', 'PO'],
  },
  {
    id: 'canonical',
    sequence: 3,
    title: 'FreightBridge Normalizes the Shipment',
    shortLabel: 'Canonical',
    source: 'FreightBridge Domain Processor',
    observed: 'A canonical shipment exists inside FreightBridge.',
    whyItMatters: 'FreightBridge converts partner-specific messages into one internal shipment language so Apex JSON is not tightly coupled to Midwest X12.',
    analystChecks: ['Load ID survived translation', 'Origin and destination survived translation', 'BOL and PO are preserved when available', 'Equipment, weight, pieces, and dates remain usable'],
    healthySignal: 'The canonical shipment has enough business data to map into the carrier 204.',
    correlationFields: ['Shipment Number', 'BOL', 'PO'],
  },
  {
    id: 'x12-204',
    sequence: 4,
    title: 'FreightBridge Builds the 204',
    shortLabel: '204',
    source: 'FreightBridge X12 Mapper',
    observed: 'FreightBridge generated an X12 204 Motor Carrier Load Tender for Midwest.',
    whyItMatters: 'The 204 asks Midwest, in plain English, "Will you haul this load?" Apex did not generate this EDI document.',
    analystChecks: ['Target partner is Midwest Carrier', 'X12 version is 004010', 'ST segment identifies transaction set 204', 'Required shipment fields mapped', 'Control numbers exist'],
    healthySignal: 'A safe 204 payload exists and can be correlated back to the Apex shipment.',
    correlationFields: ['ISA13', 'GS06', 'ST02', 'Load ID'],
    technicalDetails: 'ISA is the interchange envelope, GS is the functional group, and ST is the transaction set. ST*204 identifies a 204 load tender.',
    rawEvidenceTitle: 'Inspect Raw X12',
    questionId: 'who-created-204',
  },
  {
    id: 'sftp-delivery',
    sequence: 5,
    title: 'The 204 Leaves FreightBridge',
    shortLabel: 'SFTP',
    source: 'FreightBridge SFTP Transport',
    observed: 'FreightBridge recorded outbound SFTP delivery metadata for the 204.',
    whyItMatters: 'Document creation and document delivery are different. A 204 existing does not prove Midwest received it.',
    analystChecks: ['Outbound file name exists', 'Remote path is recorded', 'Delivery disposition succeeded', 'No credentials are exposed'],
    healthySignal: 'FreightBridge can show safe transport evidence for the outbound file.',
    correlationFields: ['File Name', 'Remote Path', '204 Control Numbers'],
    questionId: 'sftp-not-business-acceptance',
  },
  {
    id: 'x12-997',
    sequence: 6,
    title: 'Midwest Technically Acknowledges It',
    shortLabel: '997',
    source: 'Inbound Midwest EDI',
    observed: 'FreightBridge received a 997 Functional Acknowledgment from Midwest.',
    whyItMatters: 'A 997 proves Midwest received and structurally processed the EDI. It does not prove the carrier accepted the load.',
    analystChecks: ['Acknowledged group control number matches the 204', 'Acknowledged transaction control number matches the 204', 'AK5/AK9 status is accepted or rejected', 'Next expected business evidence is 990'],
    healthySignal: 'The 997 correlates to the outbound 204 and reports technical acceptance.',
    correlationFields: ['204 GS06', '204 ST02', '997 AK1', '997 AK2'],
    questionId: 'technical-ack',
  },
  {
    id: 'x12-990',
    sequence: 7,
    title: 'Midwest Makes the Business Decision',
    shortLabel: '990',
    source: 'Inbound Midwest EDI',
    observed: 'FreightBridge received a 990 Response to Load Tender.',
    whyItMatters: 'The 990 is the carrier business answer: accepted or rejected.',
    analystChecks: ['Decision is accepted or rejected', 'Decision correlates to the same load', 'FreightBridge updates the broker-facing side when applicable'],
    healthySignal: 'For this healthy run, the real tender result is accepted.',
    correlationFields: ['Load ID', 'Carrier Load Reference', 'BOL', 'PO'],
    questionId: 'tender-response',
  },
  {
    id: 'x12-214',
    sequence: 8,
    title: 'Shipment Status Starts Moving',
    shortLabel: '214',
    source: 'Inbound Midwest EDI',
    observed: 'FreightBridge received 214 shipment status events.',
    whyItMatters: 'The 214 reports what is happening to the shipment, such as picked up, in transit, arrived, and delivered.',
    analystChecks: ['AT7 status maps to a supported status', 'Business event time is captured', 'Received time may differ from event time', 'Apex-facing status is updated when applicable'],
    healthySignal: 'Status events correlate to the load and preserve event history without moving current status backward.',
    correlationFields: ['Load ID', '214 ST02', 'Event Time', 'Status Code'],
    questionId: 'status-message',
  },
  {
    id: 'apex-update',
    sequence: 9,
    title: 'FreightBridge Updates Apex',
    shortLabel: 'Apex Update',
    source: 'FreightBridge Outbound Partner Update',
    observed: 'FreightBridge verifies broker-facing tender/status evidence from the Apex side of the integration.',
    whyItMatters: 'The learner should verify FreightBridge-side callback or reconciliation evidence, not Apex private systems.',
    analystChecks: ['Destination partner is Apex', 'Business result/status is normalized', 'Safe response metadata or reconciliation exists'],
    healthySignal: 'Apex-facing tender/status evidence matches what FreightBridge processed from Midwest.',
    correlationFields: ['Load ID', 'Tender Status', 'Shipment Status'],
  },
  {
    id: 'healthy-confirmed',
    sequence: 10,
    title: 'Healthy Flow Confirmed',
    shortLabel: 'Healthy',
    source: 'FreightBridge Training Review',
    observed: 'The full shipment lifecycle completed successfully.',
    whyItMatters: 'This is your baseline. Future incident missions compare a broken flow against these healthy checkpoints.',
    analystChecks: ['Identify the last healthy checkpoint', 'Confirm the evidence does not stop early', 'Summarize what normal looks like'],
    healthySignal: 'Inbound, mapping, delivery, technical acknowledgment, business response, status flow, and broker-facing update evidence are complete.',
    correlationFields: ['Load ID', 'Lab Run ID', 'Transaction IDs'],
  },
];

export const inboundRequestQuestion: KnowledgeCheckQuestion = {
  id: 'inbound-does-not-prove-midwest',
  prompt: 'Does receiving the Apex request prove Midwest has seen the load?',
  options: [
    { id: 'yes', label: 'Yes' },
    { id: 'no', label: 'No' },
  ],
  correctOptionId: 'no',
  explanation: 'Correct: the request reached FreightBridge, but no Midwest evidence exists yet.',
};

export const generated204Question: KnowledgeCheckQuestion = {
  id: 'who-created-204',
  prompt: 'Who created the X12 204 for Midwest?',
  options: [
    { id: 'apex', label: 'Apex Logistics' },
    { id: 'freightbridge', label: 'FreightBridge' },
    { id: 'midwest', label: 'Midwest Carrier' },
  ],
  correctOptionId: 'freightbridge',
  explanation: 'Correct: FreightBridge generated the 204 from the Apex request and canonical shipment.',
};

export const sftpDeliveryQuestion: KnowledgeCheckQuestion = {
  id: 'sftp-not-business-acceptance',
  prompt: 'Does successful SFTP delivery mean Midwest accepted the load?',
  options: [
    { id: 'yes', label: 'Yes' },
    { id: 'no', label: 'No' },
  ],
  correctOptionId: 'no',
  explanation: 'Correct: SFTP only proves delivery evidence. The 990 carries the business decision.',
};

export const missionOneTeachingSteps: TeachingStep[] = [
  {
    id: 'inbound-request',
    title: 'FreightBridge received an inbound request from Apex',
    plainLanguage: 'From your workstation, the first fact is not what Apex did internally. It is that FreightBridge received an authenticated REST/JSON load request from Apex.',
    advancedDetails: 'The real Lab run creates an Apex load and dispatches it through the existing FreightBridge inbound API path.',
    source: 'FreightBridge API Gateway',
    observed: 'Inbound REST/JSON request from APEX',
    analystCheck: ['Did FreightBridge receive it?', 'Which partner sent it?', 'What HTTP response did FreightBridge return?'],
  },
  {
    id: 'canonical-model',
    title: 'FreightBridge created a canonical shipment',
    plainLanguage: 'FreightBridge translated the partner-specific JSON into its internal shipment language before generating any EDI.',
    advancedDetails: 'The Canonical Shipment Model keeps Apex JSON from being tightly coupled to Midwest X12.',
    source: 'FreightBridge Domain Processor',
    observed: 'Canonical shipment data available',
    analystCheck: ['Did parsing succeed?', 'Did business validation pass?', 'Was a canonical shipment created?'],
  },
  {
    id: 'x12-204',
    title: 'FreightBridge generated an X12 204 for Midwest',
    plainLanguage: 'The X12 204 Motor Carrier Load Tender asks Midwest whether they will haul the load.',
    advancedDetails: 'Apex did not send this 204. FreightBridge generated it from Apex JSON, canonical shipment data, and the active Midwest mapping profile.',
    source: 'FreightBridge X12 Mapper',
    observed: '204 Motor Carrier Load Tender generated',
    analystCheck: ['Was the mapping successful?', 'Which mapping profile was used?', 'Was X12 produced safely?'],
  },
  {
    id: 'sftp',
    title: 'FreightBridge attempted SFTP delivery',
    plainLanguage: "FreightBridge placed the 204 in Midwest's SFTP inbox using its configured transport.",
    advancedDetails: 'Transport evidence includes file name, remote path, archive/error handling, host-key verification, and delivery disposition.',
    source: 'FreightBridge SFTP Transport',
    observed: '204 upload metadata visible to FreightBridge',
    analystCheck: ['Was an upload attempted?', 'Which remote path was used?', 'Did delivery report success or failure?'],
  },
  {
    id: 'x12-997',
    title: 'FreightBridge received a 997 from Midwest',
    plainLanguage: 'The 997 means Midwest technically acknowledged the EDI document structure. It does not mean they accepted the load.',
    advancedDetails: 'A 997 is a functional acknowledgment. It correlates back to the outbound 204 controls.',
    source: 'Inbound Midwest EDI',
    observed: '997 functional acknowledgment received',
    analystCheck: ['Did Midwest technically acknowledge the document?', 'Which 204 controls were acknowledged?'],
  },
  {
    id: 'x12-990',
    title: 'FreightBridge received a 990 tender response',
    plainLanguage: 'The 990 tells FreightBridge whether Midwest accepted or rejected the actual load tender.',
    advancedDetails: '997 = technical acknowledgment. 990 = business tender decision.',
    source: 'Inbound Midwest EDI',
    observed: '990 tender response received',
    analystCheck: ['Was the tender accepted or rejected?', 'Did FreightBridge update Apex?'],
  },
  {
    id: 'x12-214',
    title: 'FreightBridge received 214 shipment updates',
    plainLanguage: 'The 214 tells FreightBridge which shipment event Midwest reported, such as picked up, in transit, arrived, or delivered.',
    advancedDetails: 'FreightBridge maps AF to PICKED_UP, X6 to IN_TRANSIT, X1 to ARRIVED, and D1 to DELIVERED.',
    source: 'Inbound Midwest EDI',
    observed: '214 shipment event history received',
    analystCheck: ['Which business event occurred?', 'What timestamp did Midwest report?', 'Was Apex notified?'],
  },
  {
    id: 'out-of-order',
    title: 'FreightBridge protects current shipment status',
    plainLanguage: 'Messages can arrive out of order. FreightBridge keeps the full history and protects current status using event time.',
    advancedDetails: 'If DELIVERED is received before a late ARRIVED message, FreightBridge keeps both events in history but leaves current shipment status as DELIVERED.',
    source: 'FreightBridge Shipment Status Processor',
    observed: 'Event history preserved with current status protected',
    analystCheck: ['Did event time differ from received time?', 'Was current status changed correctly?'],
  },
];

export const technicalAckQuestion: KnowledgeCheckQuestion = {
  id: 'technical-ack',
  prompt: 'From your FreightBridge workstation, you see a 997 from Midwest. Does that mean Midwest accepted the load?',
  options: [
    { id: 'yes', label: 'Yes' },
    { id: 'no', label: 'No' },
  ],
  correctOptionId: 'no',
  explanation: 'Correct: the 997 only confirms the EDI document was received and structurally processed. The 990 carries the business acceptance or rejection.',
};

export const tenderResponseQuestion: KnowledgeCheckQuestion = {
  id: 'tender-response',
  prompt: 'Which message tells FreightBridge whether Midwest accepted the actual load?',
  options: [
    { id: '204', label: '204' },
    { id: '997', label: '997' },
    { id: '990', label: '990' },
    { id: '214', label: '214' },
  ],
  correctOptionId: '990',
  explanation: 'Correct: the 990 is the tender response. It is the carrier business decision.',
};

export const statusMessageQuestion: KnowledgeCheckQuestion = {
  id: 'status-message',
  prompt: 'Which transaction communicates shipment status?',
  options: [
    { id: '204', label: '204' },
    { id: '997', label: '997' },
    { id: '990', label: '990' },
    { id: '214', label: '214' },
  ],
  correctOptionId: '214',
  explanation: 'Correct: the 214 carries shipment status updates.',
};

export const checkpointQuestions: KnowledgeCheckQuestion[] = [
  inboundRequestQuestion,
  generated204Question,
  sftpDeliveryQuestion,
  technicalAckQuestion,
  tenderResponseQuestion,
  statusMessageQuestion,
];

export const finalQuizQuestions = checkpointQuestions;

export const healthyChecklistItems: HealthyChecklistItem[] = [
  { id: 'inbound', label: 'Inbound request reached FreightBridge', evidence: 'Apex REST/JSON evidence exists for the load.' },
  { id: 'validation', label: 'Authentication, parsing, and validation succeeded', evidence: 'The load moved into FreightBridge processing.' },
  { id: 'canonical', label: 'Canonical shipment was created', evidence: 'Shipment data survived translation into FreightBridge format.' },
  { id: 'x12', label: 'FreightBridge generated the 204', evidence: 'X12 004010 204 and control metadata exist.' },
  { id: 'sftp', label: 'SFTP transport succeeded', evidence: 'Outbound file and remote path evidence exist.' },
  { id: 'ack997', label: '997 technically acknowledged the EDI', evidence: 'AK1/AK2 correlation confirms the 204 was acknowledged.' },
  { id: 'response990', label: '990 provided the business acceptance', evidence: 'Tender status is accepted for this healthy run.' },
  { id: 'events214', label: '214 events were processed', evidence: 'Shipment status history is available.' },
  { id: 'currentStatus', label: 'Current shipment status is correct', evidence: 'FreightBridge protects current status while preserving history.' },
  { id: 'lastHealthy', label: 'Last Healthy Checkpoint is the completed lifecycle', evidence: 'The full scenario reached SUCCEEDED.' },
];

export const missionPhases: MissionPhase[] = ['BRIEFING', 'INVESTIGATE', 'DIAGNOSE', 'PLAN', 'ACT', 'VERIFY', 'REPORT', 'DEBRIEF'];
export const flowIcon = GitBranch;

export const incidentMissions: IncidentMissionDefinition[] = [
  {
    id: APEX_BAD_AUTH_MISSION_ID,
    slug: 'apex-bad-auth',
    missionNumber: 2,
    title: "Mission 2 - Apex Can't Get a Load Through",
    shortTitle: 'Apex authentication failure',
    scenarioKey: APEX_BAD_AUTH_MISSION_ID,
    symptom: 'Apex says FreightBridge refused the request before a load was created.',
    briefing: {
      kind: 'manager',
      from: 'Mike',
      role: 'Integration Manager',
      body:
        'Apex says their load tender is not getting through. Stay inside FreightBridge evidence: did the request reach us, where did processing stop, and what can we safely ask them to retry?',
    },
    partnerMessage: {
      kind: 'partner',
      from: 'Apex Integration Support',
      role: 'External Partner Message',
      body:
        'We attempted to send a new load tender and received an error from FreightBridge. Please confirm whether the load entered processing on your side.',
    },
    evidencePoints: [
      {
        id: 'received',
        checkpoint: 'Inbound request received',
        status: 'SUCCEEDED',
        source: 'FreightBridge Inbound API',
        observed: 'FreightBridge recorded the inbound Apex REST request.',
        meaning: 'The message reached FreightBridge. The first failure is later than request receipt.',
      },
      {
        id: 'authentication',
        checkpoint: 'Partner authentication',
        status: 'FAILED',
        source: 'FreightBridge Authentication',
        observed: 'The request did not establish a trusted Apex partner identity.',
        meaning: 'FreightBridge stopped the request before it could parse or validate the load payload.',
      },
      {
        id: 'json',
        checkpoint: 'JSON parsing',
        status: 'NOT_REACHED',
        source: 'FreightBridge Inbound Processor',
        observed: 'No JSON parsing step completed for this request.',
        meaning: 'NOT REACHED does not mean the parser failed; processing stopped during authentication first.',
      },
      {
        id: 'canonical',
        checkpoint: 'Canonical shipment',
        status: 'NOT_REACHED',
        source: 'FreightBridge Domain Processor',
        observed: 'No canonical shipment was created.',
        meaning: 'Nothing should be sent to Midwest because the inbound request never became an authenticated shipment.',
      },
    ],
    lastHealthyOptions: [
      { id: 'received', label: 'Inbound request was received by FreightBridge', explanation: 'Correct. FreightBridge recorded the request before authentication became the first failed checkpoint.' },
      { id: 'authenticated', label: 'Partner authentication succeeded', explanation: 'Authentication is the first failed checkpoint in this incident.' },
      { id: 'parsed', label: 'JSON parsed successfully', explanation: 'JSON parsing was not reached because authentication failed first.' },
    ],
    correctLastHealthyId: 'received',
    diagnosisOptions: [
      { id: 'auth', label: 'Apex request failed FreightBridge authentication', explanation: 'Correct. The real drill observed AUTHENTICATION_ERROR at the AUTHENTICATION stage.' },
      { id: 'syntax', label: 'Apex sent malformed JSON', explanation: 'Malformed JSON would fail at the parsing stage, not authentication.' },
      { id: 'midwest', label: 'Midwest rejected the tender', explanation: 'The flow never reached Midwest or X12 generation.' },
    ],
    correctDiagnosisId: 'auth',
    planOptions: [
      { id: 'retry-auth', label: 'Ask Apex to retry with valid training authentication, then verify a healthy lifecycle', explanation: 'Correct. This is a safe retry after correcting the request identity problem.' },
      { id: 'manual-midwest', label: 'Manually create the Midwest 204', explanation: 'Do not create downstream carrier work from an unauthenticated request.' },
      { id: 'ignore', label: 'Mark the load successful', explanation: 'No FreightBridge evidence supports a successful load.' },
    ],
    correctPlanId: 'retry-auth',
    remediationLabel: 'Retry with valid training authentication',
    verification: 'The retry must pass authentication, parse, validate, create a canonical shipment, and complete the healthy FreightBridge lifecycle.',
    statusPrompt: 'Write Mike a short update that explains the stop point, diagnosis, safe action, and recovery evidence.',
    debrief: [
      'Authentication failures happen before FreightBridge can safely trust or parse a partner payload.',
      'The last healthy checkpoint is request receipt; partner authentication is the first failed checkpoint.',
      'Recovery is proven by a fresh healthy run, not by changing the failed transaction to look successful.',
    ],
    hints: [
      { id: 'stage', label: 'Hint 1 - Check the stage', body: 'AUTHENTICATION means the failure occurred before JSON parsing or business validation.' },
      { id: 'boundary', label: 'Hint 2 - Respect the evidence boundary', body: 'FreightBridge can prove request-boundary evidence; it cannot inspect Apex internal token handling.' },
      { id: 'sequence', label: 'Hint 3 - Strong clue', body: 'If authentication does not succeed, JSON parsing and downstream EDI cannot begin.' },
    ],
  },
  {
    id: APEX_INVALID_JSON_MISSION_ID,
    slug: 'apex-invalid-json',
    missionNumber: 3,
    title: "Mission 3 - The Request Arrived, But FreightBridge Can't Read It",
    shortTitle: 'Malformed Apex JSON',
    scenarioKey: APEX_INVALID_JSON_MISSION_ID,
    symptom: 'Apex says the request reached FreightBridge, but the load still did not enter processing.',
    briefing: {
      kind: 'manager',
      from: 'Mike',
      role: 'Integration Manager',
      body:
        'This one is different: the request reached us with a partner identity, but FreightBridge could not read the body. Prove whether the failure is transport, parsing, validation, or downstream EDI.',
    },
    partnerMessage: {
      kind: 'partner',
      from: 'Apex Integration Support',
      role: 'External Partner Message',
      body:
        'We got a FreightBridge error after submitting the load tender. Our team believes the request was sent, but the load is not visible downstream.',
    },
    evidencePoints: [
      {
        id: 'received',
        checkpoint: 'Inbound request received',
        status: 'SUCCEEDED',
        source: 'FreightBridge Inbound API',
        observed: 'The Apex REST request reached FreightBridge.',
        meaning: 'Transport and request receipt succeeded.',
      },
      {
        id: 'authentication',
        checkpoint: 'Partner authentication',
        status: 'SUCCEEDED',
        source: 'FreightBridge Authentication',
        observed: 'FreightBridge accepted the configured Apex training identity.',
        meaning: 'Authentication is healthy, so the failure is later in the inbound pipeline.',
      },
      {
        id: 'parsing',
        checkpoint: 'JSON parsing',
        status: 'FAILED',
        source: 'FreightBridge Inbound Parser',
        observed: 'FreightBridge could not turn the request body into structured JSON data.',
        meaning: 'The body could not become structured load data.',
      },
      {
        id: 'validation',
        checkpoint: 'Business validation',
        status: 'NOT_REACHED',
        source: 'FreightBridge Validation Layer',
        observed: 'No Apex contract validation ran because parsing failed first.',
        meaning: 'Do not diagnose missing business fields until the JSON is parseable.',
      },
    ],
    lastHealthyOptions: [
      { id: 'authentication', label: 'Partner authentication succeeded', explanation: 'Correct. Authentication succeeded immediately before JSON parsing failed.' },
      { id: 'validation', label: 'Business validation passed', explanation: 'Validation was not reached because parsing failed.' },
      { id: 'x12', label: 'Midwest 204 generated', explanation: 'No downstream EDI is created from malformed JSON.' },
    ],
    correctLastHealthyId: 'authentication',
    diagnosisOptions: [
      { id: 'json', label: 'Apex sent malformed JSON that failed parsing', explanation: 'Correct. The observed failure is INVALID_JSON at PARSING.' },
      { id: 'auth', label: 'Apex failed authentication', explanation: 'Authentication is not the stop point for this mission.' },
      { id: 'contract', label: 'A required load field was missing', explanation: 'Contract validation did not run because FreightBridge could not parse the body.' },
    ],
    correctDiagnosisId: 'json',
    planOptions: [
      { id: 'retry-json', label: 'Ask Apex to resend parseable JSON and verify the healthy lifecycle', explanation: 'Correct. The safe action is a corrected payload retry.' },
      { id: 'patch-db', label: 'Insert the load directly into the database', explanation: 'Bypassing the inbound contract would hide the integration failure.' },
      { id: 'wait-midwest', label: 'Wait for Midwest to send a 990', explanation: 'Midwest never received a 204 for this failed inbound request.' },
    ],
    correctPlanId: 'retry-json',
    remediationLabel: 'Retry with corrected JSON',
    verification: 'The retry must move beyond parsing into validation and complete the normal lifecycle.',
    statusPrompt: 'Write Mike an update that separates request arrival from parseable content and includes recovery evidence.',
    debrief: [
      'Request arrival is not the same as readable JSON.',
      'The last healthy checkpoint is successful partner authentication; parsing is the first failed checkpoint.',
      'Recovery is verified only when a corrected request completes the full healthy flow.',
    ],
    hints: [
      { id: 'arrival', label: 'Hint 1 - Arrival is not enough', body: 'A request can reach FreightBridge and still fail before it becomes structured data.' },
      { id: 'sequence', label: 'Hint 2 - Read the stage sequence', body: 'Parsing comes before business validation and canonical shipment creation.' },
      { id: 'parser', label: 'Hint 3 - Strong clue', body: 'A contract validator cannot inspect business fields until the request body is valid JSON.' },
    ],
  },
  {
    id: APEX_INVALID_CONTRACT_MISSION_ID,
    slug: 'apex-invalid-contract',
    missionNumber: 4,
    title: 'Mission 4 - The JSON Looks Fine - Why Was It Rejected?',
    shortTitle: 'Apex contract validation failure',
    scenarioKey: APEX_INVALID_CONTRACT_MISSION_ID,
    symptom: 'Apex says the JSON looks valid, but FreightBridge rejected the tender.',
    briefing: {
      kind: 'manager',
      from: 'Mike',
      role: 'Integration Manager',
      body:
        'Now the JSON parses, but FreightBridge still rejects the request. Find the difference between syntax success and business contract success, then prove the retry is healthy.',
    },
    partnerMessage: {
      kind: 'partner',
      from: 'Apex Integration Support',
      role: 'External Partner Message',
      body:
        'The request body is valid JSON and includes the load details we expected. Please explain why FreightBridge rejected it.',
    },
    evidencePoints: [
      {
        id: 'received',
        checkpoint: 'Inbound request received',
        status: 'SUCCEEDED',
        source: 'FreightBridge Inbound API',
        observed: 'The Apex request reached FreightBridge.',
        meaning: 'Transport and request receipt succeeded.',
      },
      {
        id: 'authentication',
        checkpoint: 'Partner authentication',
        status: 'SUCCEEDED',
        source: 'FreightBridge Authentication',
        observed: 'FreightBridge accepted the configured Apex training identity.',
        meaning: 'The request passed the security boundary and continued to parsing.',
      },
      {
        id: 'parsing',
        checkpoint: 'JSON parsing',
        status: 'SUCCEEDED',
        source: 'FreightBridge Inbound Parser',
        observed: 'FreightBridge parsed the JSON body successfully.',
        meaning: 'The payload is syntactically readable, so the failure is later.',
      },
      {
        id: 'validation',
        checkpoint: 'Apex load contract validation',
        status: 'FAILED',
        source: 'FreightBridge Validation Layer',
        observed: 'FreightBridge parsed the JSON but rejected the load before canonical shipment creation.',
        meaning: 'A valid JSON document can still violate FreightBridge business contract rules.',
      },
    ],
    lastHealthyOptions: [
      { id: 'parsing', label: 'JSON parsing succeeded', explanation: 'Correct. Validation is the first failed checkpoint.' },
      { id: 'canonical', label: 'Canonical shipment created', explanation: 'No canonical shipment was created after contract validation failed.' },
      { id: 'midwest', label: 'Midwest technically acknowledged the 204', explanation: 'The flow never reached Midwest.' },
    ],
    correctLastHealthyId: 'parsing',
    diagnosisOptions: [
      { id: 'contract', label: 'Parsed JSON failed the Apex load contract', explanation: 'Correct. The observed failure is INVALID_APEX_LOAD at VALIDATION.' },
      { id: 'syntax', label: 'FreightBridge could not parse JSON', explanation: 'Parsing succeeded in this mission.' },
      { id: 'sftp', label: 'SFTP delivery to Midwest failed', explanation: 'No 204 or SFTP delivery was attempted.' },
    ],
    correctDiagnosisId: 'contract',
    planOptions: [
      { id: 'retry-contract', label: 'Ask Apex to resend a contract-valid payload and verify the healthy lifecycle', explanation: 'Correct. The retry must include required business fields.' },
      { id: 'skip-field', label: 'Ignore the missing postal code and force the shipment downstream', explanation: 'Forcing incomplete shipment data would create unsafe downstream work.' },
      { id: 'carrier-fix', label: 'Ask Midwest to accept the tender manually', explanation: 'Midwest has no tender to accept.' },
    ],
    correctPlanId: 'retry-contract',
    remediationLabel: 'Retry with contract-valid payload',
    verification: 'The retry must pass validation, create canonical shipment evidence, and complete the healthy lifecycle.',
    statusPrompt: 'Write Mike an update that explains parsing succeeded, validation failed, and the retry proved recovery.',
    debrief: [
      'Syntactically valid JSON is not automatically business-valid.',
      'The last healthy checkpoint is parsing; the first failed checkpoint is Apex contract validation.',
      'A safe retry proves the required business fields were corrected without weakening validation.',
    ],
    hints: [
      { id: 'json', label: 'Hint 1 - Valid JSON is only syntax', body: 'Business validation checks whether required shipment fields are present and usable.' },
      { id: 'missing-field', label: 'Hint 2 - Inspect safe payload preview', body: 'The drill preview shows pickup.postalCode as REMOVED, which explains the contract failure.' },
      { id: 'contract', label: 'Hint 3 - Strong clue', body: 'Parsing succeeded, so compare required contract fields rather than JSON syntax or Midwest transport.' },
    ],
  },
  {
    id: DUPLICATE_SHIPMENT_MISSION_ID,
    slug: 'duplicate-shipment',
    missionNumber: 5,
    title: 'Mission 5 - Why Is This Shipment Showing Up Twice?',
    shortTitle: 'Duplicate shipment protection',
    scenarioKey: 'APEX_DUPLICATE_SHIPMENT',
    symptom: 'Apex reports that a retried load did not behave like a new shipment, and they want to know what FreightBridge did with the second attempt.',
    briefing: {
      kind: 'manager',
      from: 'Mike',
      role: 'Integration Manager',
      body:
        'Apex says a load was retried and something about the second attempt looks wrong. Do not assume it is a system outage. Correlate the requests, identify whether the second attempt is a legitimate new shipment, and prove what FreightBridge protected.',
    },
    partnerMessage: {
      kind: 'partner',
      from: 'Apex Integration Support',
      role: 'External Partner Message',
      body:
        'We resent the same load after not seeing the result we expected. Please confirm whether FreightBridge created another shipment or handled the retry differently.',
    },
    evidencePoints: [
      {
        id: 'baseline',
        checkpoint: 'Original Apex load established',
        status: 'SUCCEEDED',
        source: 'FreightBridge Inbound API',
        observed: 'A baseline Apex load request created the original FreightBridge shipment evidence.',
        meaning: 'There is already a real shipment for this business identifier.',
      },
      {
        id: 'second-request',
        checkpoint: 'Second inbound request correlated',
        status: 'SUCCEEDED',
        source: 'Business Trace',
        observed: 'The later inbound request reused the same load/business identifier.',
        meaning: 'The second request is not an unrelated shipment.',
      },
      {
        id: 'idempotency',
        checkpoint: 'Idempotency protection missing',
        status: 'FAILED',
        source: 'FreightBridge Duplicate Protection',
        observed: 'The repeated request lacked the safe replay marker FreightBridge expects for idempotent retry behavior.',
        meaning: 'FreightBridge must prevent duplicate business processing rather than creating a second shipment.',
      },
      {
        id: 'downstream',
        checkpoint: 'Duplicate downstream work',
        status: 'NOT_REACHED',
        source: 'FreightBridge Outbound Processing',
        observed: 'No second canonical shipment or duplicate downstream 204 should be produced from the duplicate attempt.',
        meaning: 'The failure protects the business process.',
      },
    ],
    evidenceSources: [
      {
        id: 'transaction',
        title: 'Transaction Evidence',
        source: 'Integration Transaction',
        summary: 'Compare the baseline successful request with the later failed duplicate attempt.',
        inspectedLabel: 'Inspect transaction pair',
        details: [
          'Same Apex load identifier appears on the original and repeated request.',
          'The baseline request created shipment evidence before the duplicate attempt.',
          'The duplicate attempt is recorded as failed rather than silently ignored.',
        ],
        rawFrom: 'steps',
      },
      {
        id: 'trace',
        title: 'Business Trace / Correlation',
        source: 'Business Trace',
        summary: 'Use business identifier correlation to prove the requests are related.',
        inspectedLabel: 'Inspect trace correlation',
        details: [
          'The second request shares the same business/load identifier as the original request.',
          'This is a repeat of the same business shipment, not a separate customer order.',
          'Related transaction IDs show FreightBridge preserved an audit trail.',
        ],
        rawFrom: 'observedFailure',
      },
      {
        id: 'idempotency',
        title: 'Replay / Idempotency Evidence',
        source: 'FreightBridge Replay Control',
        summary: 'Distinguish idempotent retry behavior from duplicate business creation.',
        inspectedLabel: 'Inspect replay evidence',
        details: [
          'A safe replay uses an idempotency key to return the prior result.',
          'This drill intentionally repeats the load without that protection.',
          'FreightBridge prevents a second shipment and duplicate downstream work.',
        ],
        rawFrom: 'failureDrill',
      },
    ],
    requiredEvidenceSourceIds: ['transaction', 'idempotency'],
    lastHealthyOptions: [
      { id: 'baseline', label: 'Original shipment was established before the duplicate retry', explanation: 'Correct. The original load is healthy; the duplicate retry is where the second path diverges.' },
      { id: 'second-created', label: 'Second shipment was created successfully', explanation: 'The second attempt failed duplicate protection and should not create another shipment.' },
      { id: 'midwest', label: 'Midwest accepted a duplicate 204', explanation: 'The duplicate attempt should not reach downstream duplicate tender processing.' },
    ],
    correctLastHealthyId: 'baseline',
    diagnosisOptions: [
      { id: 'duplicate', label: 'The same shipment was resent without an idempotency key, so FreightBridge treated the second request as a duplicate', explanation: 'Correct. The evidence shows same business ID plus missing safe replay behavior.' },
      { id: 'auth', label: 'Apex failed authentication on the retry', explanation: 'The failure is duplicate protection, not authentication.' },
      { id: 'carrier', label: 'Midwest rejected the load tender', explanation: 'The second path stopped before duplicate downstream carrier work.' },
    ],
    correctDiagnosisId: 'duplicate',
    planOptions: [
      { id: 'safe-replay', label: 'Use safe replay/idempotent retry evidence rather than creating another shipment', explanation: 'Correct. The recovery is proving the original remains established and duplicate processing was suppressed.' },
      { id: 'force-new', label: 'Force a second canonical shipment with the same load ID', explanation: 'That would create duplicate business processing.' },
      { id: 'change-load', label: 'Change the load number and submit it as new freight', explanation: 'Changing the business identifier hides the duplicate/replay issue.' },
    ],
    correctPlanId: 'safe-replay',
    remediationLabel: 'Verify safe replay protection',
    recoveryMode: 'INCIDENT_VERIFICATION',
    verification: 'Verification must keep the same load identifier, confirm the original shipment exists, and prove duplicate downstream business processing was not created.',
    statusPrompt: 'Write Mike an update covering Apex claim, same-load correlation, missing idempotency protection, duplicate suppression, and recovery evidence.',
    debrief: [
      'A retry and a duplicate are not the same thing.',
      'The last healthy checkpoint is the original shipment establishment; the duplicate retry is where the second path diverged.',
      'FreightBridge protected the business process by preventing duplicate downstream shipment creation.',
      'A safe replay should preserve correlation to the original result rather than creating another shipment.',
    ],
    hints: [
      { id: 'source', label: 'Hint 1 - Start with correlation', body: 'Compare the load/business identifier on the original request and the repeated request.' },
      { id: 'fields', label: 'Hint 2 - Inspect replay evidence', body: 'Look for whether the second attempt was an idempotent replay or just the same shipment sent again.' },
      { id: 'concept', label: 'Hint 3 - Technical concept', body: 'Idempotent replay returns a prior result safely; a duplicate business transaction tries to create work twice.' },
    ],
  },
  {
    id: X12_ENVELOPE_MISMATCH_MISSION_ID,
    slug: 'x12-envelope-mismatch',
    missionNumber: 6,
    title: 'Mission 6 - Midwest Sent the Status, But FreightBridge Rejected It',
    shortTitle: '214 control-number mismatch',
    scenarioKey: 'X12_214_CONTROL_MISMATCH',
    symptom: 'Midwest says they sent a shipment-status file, while Apex has no matching status update.',
    briefing: {
      kind: 'manager',
      from: 'Mike',
      role: 'Integration Manager',
      body:
        'Midwest says a 214 status file was sent, but Apex never received the status. File arrival is only one checkpoint. Inspect the raw X12 and transaction evidence before deciding where the flow stopped.',
    },
    partnerMessage: {
      kind: 'partner',
      from: 'Midwest EDI Support',
      role: 'External Partner Message',
      body:
        'We placed the shipment-status 214 for the load in the expected SFTP location. Please check why FreightBridge did not forward a status update.',
    },
    evidencePoints: [
      {
        id: 'sftp',
        checkpoint: '214 file reached FreightBridge',
        status: 'SUCCEEDED',
        source: 'FreightBridge SFTP Intake',
        observed: 'A Midwest 214 file reached the FreightBridge-controlled inbound boundary.',
        meaning: 'File arrival is proven, but processability is not.',
      },
      {
        id: 'transaction-set',
        checkpoint: 'X12 transaction set',
        status: 'FAILED',
        source: 'FreightBridge X12 Parser',
        observed: 'The transaction-set control evidence fails before normal 214 mapping can continue.',
        meaning: 'The flow stopped during X12 parsing, not carrier business-status mapping.',
      },
      {
        id: 'mapping',
        checkpoint: '214 status mapping',
        status: 'NOT_REACHED',
        source: 'Midwest 214 Mapper',
        observed: 'FreightBridge does not map status from a transaction set that failed envelope validation.',
        meaning: 'No Apex-facing status update should exist for the failed file.',
      },
    ],
    evidenceSources: [
      {
        id: 'sftp',
        title: 'SFTP Intake Evidence',
        source: 'FreightBridge SFTP Poller',
        summary: 'Confirm the file reached FreightBridge before parsing failed.',
        inspectedLabel: 'Inspect SFTP evidence',
        details: [
          'The source is Midwest over SFTP.',
          'The document type is 214 shipment status.',
          'File arrival alone does not prove X12 parsing succeeded.',
        ],
        rawFrom: 'x12Fault',
      },
      {
        id: 'raw-x12',
        title: 'Raw X12 Control Evidence',
        source: 'X12 Document',
        summary: 'Compare the transaction control value in ST02 with the ending value in SE02.',
        inspectedLabel: 'Inspect raw X12',
        details: [
          'ST starts the 214 transaction set and carries the transaction control number.',
          'SE ends the transaction set and must repeat the same control number.',
          'In this incident, ST02 and SE02 do not match.',
        ],
        rawFrom: 'payloadPreview',
      },
      {
        id: 'trace',
        title: 'Business Trace Evidence',
        source: 'Business Trace',
        summary: 'Verify there is no successful normalized status from the failed 214.',
        inspectedLabel: 'Inspect trace evidence',
        details: [
          'The load identifier can be correlated to the failed 214.',
          'Parsing failure prevents normal 214 mapping.',
          'Apex-facing status evidence should not appear from the rejected file.',
        ],
        rawFrom: 'observedFailure',
      },
    ],
    requiredEvidenceSourceIds: ['sftp', 'raw-x12'],
    lastHealthyOptions: [
      { id: 'file-arrival', label: '214 file reached FreightBridge SFTP intake', explanation: 'Correct. The file arrived, but valid transaction-set parsing did not complete.' },
      { id: 'mapping', label: '214 status mapping succeeded', explanation: 'Mapping was not reached after X12 control validation failed.' },
      { id: 'apex-update', label: 'Apex-facing status update was sent', explanation: 'No Apex status update should be produced from the failed 214.' },
    ],
    correctLastHealthyId: 'file-arrival',
    diagnosisOptions: [
      { id: 'control', label: 'The 214 arrived, but ST02 and SE02 transaction control numbers do not match, so parsing rejected it', explanation: 'Correct. The mismatch stops processing before mapping.' },
      { id: 'unsupported-status', label: 'The 214 contained an unsupported AT7 status code', explanation: 'That is a mapping failure, but this incident fails earlier during parsing.' },
      { id: 'sftp-missing', label: 'Midwest never sent the file', explanation: 'FreightBridge evidence shows the file reached the SFTP boundary.' },
    ],
    correctDiagnosisId: 'control',
    planOptions: [
      { id: 'correct-controls', label: 'Correct the 214 transaction-set control numbers and safely reprocess the correlated status', explanation: 'Correct. The retry must use matching ST02/SE02 values.' },
      { id: 'skip-parse', label: 'Bypass X12 parsing and create an Apex status manually', explanation: 'Do not bypass envelope validation.' },
      { id: 'ask-apex', label: 'Ask Apex to resend the status', explanation: 'Apex is downstream and did not send the Midwest 214.' },
    ],
    correctPlanId: 'correct-controls',
    remediationLabel: 'Retry corrected 214 controls',
    recoveryMode: 'HEALTHY_RETRY',
    verification: 'The corrected retry must preserve the same load, pass parsing, and progress into valid 214 status processing.',
    statusPrompt: 'Write Mike an update covering file arrival, control-number mismatch, parsing stop point, corrective action, and proof of recovery.',
    debrief: [
      'File arrival is not the same as valid X12 parsing.',
      'The last healthy checkpoint is SFTP intake; the first failed checkpoint is transaction-set control validation.',
      'Mapping and Apex-facing status updates were not reached because ST02 and SE02 did not match.',
      'Corrected control numbers let the correlated status proceed through the normal flow.',
    ],
    hints: [
      { id: 'source', label: 'Hint 1 - Inspect raw X12', body: 'The broad evidence source is the raw 214 transaction set.' },
      { id: 'fields', label: 'Hint 2 - Correlate fields', body: 'Compare the control value in ST with the control value in SE.' },
      { id: 'concept', label: 'Hint 3 - Technical concept', body: 'The transaction set begins with ST and ends with SE; their control numbers must correspond.' },
    ],
  },
  {
    id: STATUS_CALLBACK_MISSING_MISSION_ID,
    slug: 'status-callback-missing',
    missionNumber: 7,
    title: "Mission 7 - Midwest Sent the Status. Why Didn't Apex Get It?",
    shortTitle: 'Unsupported 214 status mapping',
    scenarioKey: 'X12_214_UNSUPPORTED_STATUS',
    symptom: 'Midwest says they sent the status, and Apex says no status update arrived.',
    briefing: {
      kind: 'manager',
      from: 'Mike',
      role: 'Integration Manager',
      body:
        'Both partners may be telling the truth from their own vantage point. Prove whether the 214 arrived, whether X12 parsing worked, and whether FreightBridge could map the status into an Apex-facing update.',
    },
    partnerMessage: {
      kind: 'partner',
      from: 'Midwest EDI Support',
      role: 'External Partner Message',
      body:
        'We sent a 214 status file for this load. Please explain why the broker side did not receive the corresponding update.',
    },
    evidencePoints: [
      {
        id: 'arrival',
        checkpoint: '214 received',
        status: 'SUCCEEDED',
        source: 'FreightBridge SFTP Intake',
        observed: 'FreightBridge received the Midwest 214 file.',
        meaning: 'Midwest file arrival can be true while Apex still sees no update.',
      },
      {
        id: 'parsing',
        checkpoint: 'X12 parsing',
        status: 'SUCCEEDED',
        source: 'FreightBridge X12 Parser',
        observed: 'The 214 is structurally valid enough to pass parsing and envelope checks.',
        meaning: 'This incident is not an envelope-control failure.',
      },
      {
        id: 'mapping',
        checkpoint: '214 status mapping',
        status: 'FAILED',
        source: 'Midwest 214 Mapper',
        observed: 'The status value is unsupported by the active Midwest 214 mapping.',
        meaning: 'Syntactically valid X12 can still fail semantic mapping.',
      },
      {
        id: 'apex-update',
        checkpoint: 'Apex-facing status update',
        status: 'NOT_REACHED',
        source: 'FreightBridge Outbound Partner Update',
        observed: 'No normalized shipment event should be sent to Apex from the unsupported status.',
        meaning: 'Apex did not receive a status because FreightBridge could not normalize it safely.',
      },
    ],
    evidenceSources: [
      {
        id: 'raw-x12',
        title: 'Raw 214 Status Evidence',
        source: 'X12 Document',
        summary: 'Inspect the AT7 segment and identify the status code Midwest sent.',
        inspectedLabel: 'Inspect raw 214',
        details: [
          'The file is a 214 shipment-status transaction.',
          'The AT7 segment carries the shipment-status code.',
          'This drill changes AT7-01 to ZZ.',
        ],
        rawFrom: 'payloadPreview',
      },
      {
        id: 'mapping',
        title: 'Active Mapping Evidence',
        source: 'Midwest 214 Mapping Profile',
        summary: 'Compare ZZ with the supported FreightBridge status mapping.',
        inspectedLabel: 'Inspect mapping evidence',
        details: [
          'Supported status codes include AF, X6, X1, and D1 in the active Midwest training profile.',
          'ZZ is not currently mapped to a canonical FreightBridge shipment status.',
          'Mapping failure prevents a normalized Apex-facing status update.',
        ],
        rawFrom: 'failureDrill',
      },
      {
        id: 'trace',
        title: 'Trace / Apex Update Evidence',
        source: 'Business Trace',
        summary: 'Confirm parsing progressed further than Mission 6 but stopped before Apex-facing status.',
        inspectedLabel: 'Inspect trace evidence',
        details: [
          'FreightBridge received and parsed the 214.',
          'The message reached status interpretation.',
          'No normalized shipment event or Apex-facing update was produced from unsupported ZZ.',
        ],
        rawFrom: 'observedFailure',
      },
    ],
    requiredEvidenceSourceIds: ['raw-x12', 'mapping'],
    lastHealthyOptions: [
      { id: 'parsed', label: '214 reached FreightBridge and passed X12 parsing', explanation: 'Correct. Supported status mapping is the first failed checkpoint.' },
      { id: 'sftp-only', label: 'SFTP delivery to FreightBridge was the last healthy point', explanation: 'The evidence goes beyond file arrival because parsing succeeded.' },
      { id: 'apex-update', label: 'Apex-facing status update succeeded', explanation: 'No normalized Apex update was created from unsupported ZZ.' },
    ],
    correctLastHealthyId: 'parsed',
    diagnosisOptions: [
      { id: 'unsupported', label: "Midwest's 214 passed parsing, but AT7-01 contained unsupported status code ZZ, so mapping stopped before Apex update", explanation: 'Correct. The failure is semantic mapping, not syntax.' },
      { id: 'control', label: 'ST02 and SE02 did not match', explanation: 'That would fail parsing, but this mission passes X12 structure and fails at mapping.' },
      { id: 'sftp', label: 'SFTP delivery failed before FreightBridge received the file', explanation: 'FreightBridge received the 214.' },
    ],
    correctDiagnosisId: 'unsupported',
    planOptions: [
      { id: 'correct-status', label: 'Confirm supported Midwest 214 status mapping and reprocess a corrected supported AT7 value', explanation: 'Correct. Use a mapped status such as AF, X6, X1, or D1.' },
      { id: 'forward-zz', label: 'Forward ZZ directly to Apex as a raw status', explanation: 'FreightBridge should not emit unsupported unmapped statuses.' },
      { id: 'ask-new-204', label: 'Ask FreightBridge to generate another 204 tender', explanation: 'The tender phase is unrelated to this status-mapping failure.' },
    ],
    correctPlanId: 'correct-status',
    remediationLabel: 'Retry corrected supported 214 status',
    recoveryMode: 'HEALTHY_RETRY',
    verification: 'The corrected retry must keep the same load, parse valid X12, map the supported status, and produce Apex-facing status evidence.',
    statusPrompt: 'Write Mike an update covering Midwest/Apex perspectives, parsing success, unsupported ZZ mapping, corrective action, and recovery proof.',
    debrief: [
      'Midwest sent a file and Apex did not receive an update; both can be true.',
      'The last healthy checkpoint is successful X12 parsing; the first failed checkpoint is supported status mapping.',
      'A syntactically valid 214 can still fail semantic mapping when AT7-01 is unsupported.',
      'A corrected supported status allows normalized shipment-event and Apex-facing evidence to appear.',
    ],
    hints: [
      { id: 'source', label: 'Hint 1 - Inspect the AT7 segment', body: 'The broad evidence source is the raw 214 status segment.' },
      { id: 'fields', label: 'Hint 2 - Compare against mapping', body: 'Find the AT7-01 value, then compare it with the active supported Midwest status codes.' },
      { id: 'concept', label: 'Hint 3 - Technical concept', body: 'Valid X12 syntax does not guarantee that every partner status code maps to a canonical FreightBridge status.' },
    ],
  },
  {
    id: WRONG_X12_VERSION_MISSION_ID,
    slug: 'wrong-x12-version',
    missionNumber: 8,
    title: 'Mission 8 - This Partner Is Sending the Wrong X12 Version',
    shortTitle: 'Unsupported Midwest X12 profile version',
    scenarioKey: 'X12_214_WRONG_VERSION',
    symptom: 'Midwest says the 214 is valid X12, but FreightBridge rejects it before creating an Apex-facing status update.',
    briefing: {
      kind: 'manager',
      from: 'Mike',
      role: 'Integration Manager',
      body:
        'This 214 is structurally readable and its shipment status is valid. Do not stop at “the X12 looks good.” Compare the version identifiers in the message with the active Midwest profile and prove where compatibility breaks.',
    },
    partnerMessage: {
      kind: 'partner',
      from: 'Midwest EDI Support',
      role: 'External Partner Message',
      body:
        'Our system generated a valid 214 and placed it in the expected SFTP location. Please confirm why FreightBridge is rejecting the file.',
    },
    evidencePoints: [
      {
        id: 'arrival',
        checkpoint: '214 file reached FreightBridge',
        status: 'SUCCEEDED',
        source: 'FreightBridge SFTP Intake',
        observed: 'FreightBridge received the Midwest 214 file.',
        meaning: 'Transport is healthy; the failure occurs after file arrival.',
      },
      {
        id: 'structure',
        checkpoint: 'X12 structure and controls',
        status: 'SUCCEEDED',
        source: 'FreightBridge X12 Parser',
        observed: 'The 214 is structurally parseable and its transaction-set controls are internally consistent.',
        meaning: 'This is not Mission 6: ST02/SE02 control validation succeeded.',
      },
      {
        id: 'profile',
        checkpoint: 'Midwest X12 version/profile compatibility',
        status: 'FAILED',
        source: 'Midwest 214 Mapping Profile',
        observed: 'The message advertises ISA12 00501 and GS08 005010, but the active Midwest profile supports 00401 / 004010.',
        meaning: 'Valid X12 syntax does not make a message compatible with the partner profile FreightBridge is configured to process.',
      },
      {
        id: 'status-mapping',
        checkpoint: '214 status mapping',
        status: 'NOT_REACHED',
        source: 'Midwest 214 Mapper',
        observed: 'The AT7 status does not become a canonical shipment event because profile compatibility fails first.',
        meaning: 'Do not diagnose the AT7 code when the version/profile gate already rejected the message.',
      },
      {
        id: 'apex-update',
        checkpoint: 'Apex-facing shipment update',
        status: 'NOT_REACHED',
        source: 'FreightBridge Outbound Partner Update',
        observed: 'No normalized status update is produced from the rejected version.',
        meaning: 'Apex sees no update because FreightBridge safely stopped incompatible partner data.',
      },
    ],
    evidenceSources: [
      {
        id: 'raw-version',
        title: 'Raw X12 Version Evidence',
        source: 'X12 Document',
        summary: 'Inspect the envelope version identifiers Midwest sent.',
        inspectedLabel: 'Inspect X12 version fields',
        details: [
          'ISA12 identifies the interchange control version used by this project profile.',
          'GS08 identifies the functional-group implementation version.',
          'This drill sends ISA12 00501 and GS08 005010.',
        ],
        rawFrom: 'payloadPreview',
      },
      {
        id: 'profile',
        title: 'Midwest Partner Profile Evidence',
        source: 'Midwest Implementation Guide / Active Profile',
        summary: 'Compare the received version identifiers with FreightBridge\'s active Midwest contract.',
        inspectedLabel: 'Inspect partner profile',
        details: [
          'Midwest\'s active FreightBridge project profile uses ISA12 00401.',
          'The active functional-group version is GS08 004010.',
          '00501 / 005010 is not accepted by the current Midwest 214 profile.',
        ],
        rawFrom: 'failureDrill',
      },
      {
        id: 'mapping',
        title: 'Mapping/Profile Failure Evidence',
        source: 'FreightBridge Integration Error',
        summary: 'Confirm the persisted failure classification occurs at MAPPING with UNSUPPORTED_X12_VERSION.',
        inspectedLabel: 'Inspect mapping classification',
        details: [
          'The error category is MAPPING_ERROR.',
          'The stage is MAPPING, not PARSING.',
          'The error code is UNSUPPORTED_X12_VERSION.',
        ],
        rawFrom: 'observedFailure',
      },
      {
        id: 'trace',
        title: 'Business Trace Evidence',
        source: 'Business Trace',
        summary: 'Verify the same load reached FreightBridge but did not produce an Apex-facing status from the incompatible 214.',
        inspectedLabel: 'Inspect trace evidence',
        details: [
          'The failed 214 remains correlated to the same shipment.',
          'No normalized shipment event should be produced from the wrong version.',
          'A corrected supported-version retry should preserve the same business identifier.',
        ],
        rawFrom: 'steps',
      },
    ],
    requiredEvidenceSourceIds: ['raw-version', 'profile', 'mapping'],
    lastHealthyOptions: [
      { id: 'structure', label: 'The 214 arrived and passed X12 structure/control validation', explanation: 'Correct. Version/profile compatibility is the first failed checkpoint.' },
      { id: 'status-map', label: 'The AT7 shipment status mapped successfully', explanation: 'Status mapping is not reached after version/profile compatibility fails.' },
      { id: 'apex', label: 'Apex received the shipment update', explanation: 'No Apex-facing status is created from the incompatible 214.' },
    ],
    correctLastHealthyId: 'structure',
    diagnosisOptions: [
      { id: 'version', label: 'The 214 is structurally valid, but ISA12 00501 / GS08 005010 do not match Midwest\'s supported 00401 / 004010 profile', explanation: 'Correct. This is profile compatibility at the mapping stage, not malformed X12.' },
      { id: 'controls', label: 'ST02 and SE02 do not match', explanation: 'Those controls match in this incident; that is the Mission 6 failure class.' },
      { id: 'status', label: 'AT7-01 contains an unsupported shipment-status code', explanation: 'The status code is not the failing field here; the message version is rejected first.' },
    ],
    correctDiagnosisId: 'version',
    planOptions: [
      { id: 'supported-version', label: 'Confirm the Midwest implementation guide, resend the same 214 using supported 00401 / 004010 version identifiers, and verify normal processing', explanation: 'Correct. Align the message with the active partner profile rather than weakening FreightBridge validation.' },
      { id: 'accept-any', label: 'Change FreightBridge to accept any X12 version automatically', explanation: 'Version compatibility is part of the partner contract and should not be bypassed blindly.' },
      { id: 'rewrite-status', label: 'Change only the AT7 shipment-status code', explanation: 'AT7 is not the incompatible field in this incident.' },
    ],
    correctPlanId: 'supported-version',
    remediationLabel: 'Retry with supported Midwest X12 version',
    recoveryMode: 'INCIDENT_VERIFICATION',
    verification: 'The corrected retry must keep the same load, use ISA12 00401 and GS08 004010, pass mapping/profile validation, and produce Apex-facing shipment-status evidence.',
    statusPrompt: 'Write Mike an update covering file arrival, valid X12 structure, received versus supported version identifiers, corrective action, and same-load recovery proof.',
    debrief: [
      'Valid X12 syntax is not the same as partner-profile compatibility.',
      'ISA12 and GS08 are evidence for the version/profile FreightBridge is being asked to process.',
      'The last healthy checkpoint is successful X12 structure/control validation; the first failed checkpoint is Midwest profile compatibility.',
      'A corrected 00401 / 004010 retry can map normally and restore Apex-facing status evidence for the same load.',
    ],
    hints: [
      { id: 'source', label: 'Hint 1 - Inspect the envelope versions', body: 'Compare ISA12 and GS08 rather than starting with AT7.' },
      { id: 'profile', label: 'Hint 2 - Check the partner contract', body: 'The Midwest implementation guide defines 004010 as the supported X12 version for this project.' },
      { id: 'concept', label: 'Hint 3 - Technical concept', body: 'A message can be structurally valid X12 and still be incompatible with the active trading-partner profile.' },
    ],
  },
];

export function findIncidentMissionBySlug(slug: string | undefined): IncidentMissionDefinition | undefined {
  return incidentMissions.find((mission) => mission.slug === slug);
}
