from dataclasses import dataclass
from enum import Enum


class X12ErrorCode(str, Enum):
  INVALID_ENCODING = 'INVALID_ENCODING'
  MALFORMED_ISA = 'MALFORMED_ISA'
  MISSING_INTERCHANGE_HEADER = 'MISSING_INTERCHANGE_HEADER'
  MISSING_INTERCHANGE_TRAILER = 'MISSING_INTERCHANGE_TRAILER'
  UNEXPECTED_ENVELOPE_SEGMENT = 'UNEXPECTED_ENVELOPE_SEGMENT'
  CONTROL_NUMBER_MISMATCH = 'CONTROL_NUMBER_MISMATCH'
  SEGMENT_COUNT_MISMATCH = 'SEGMENT_COUNT_MISMATCH'
  TRANSACTION_COUNT_MISMATCH = 'TRANSACTION_COUNT_MISMATCH'
  GROUP_COUNT_MISMATCH = 'GROUP_COUNT_MISMATCH'
  UNTERMINATED_TRANSACTION = 'UNTERMINATED_TRANSACTION'
  UNTERMINATED_GROUP = 'UNTERMINATED_GROUP'
  INVALID_ENVELOPE_COUNT = 'INVALID_ENVELOPE_COUNT'


@dataclass
class X12Error(Exception):
  code: X12ErrorCode
  message: str
  segment_id: str | None = None
  segment_index: int | None = None
  element_position: int | None = None


class X12ParseError(X12Error):
  pass


class X12ValidationError(X12Error):
  pass
